POST http://localhost:5256/Login
Content-Type: application/json

{
  "ID":"jacking751",
  "Password":"123qwe"
}

###
POST http://localhost:5256/CreateAccount
Content-Type: application/json

{
  "Email":"jacking751",
  "Password":"123qwe"
}

